version: '3.7'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: entrance
      POSTGRES_PASSWORD: heslo123

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'

volumes:
  data: